name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Optional tag name to simulate release'
        required: false

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  VERBOSE: 1

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build_and_test_msys:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - sys: mingw64
            compiler: clang
            extra_cmake_params: -DCMAKE_CXX_FLAGS=-Wno-deprecated # doctest issue #900
            os: windows-2025

    name: 'Windows MSYS2 ${{ matrix.sys }} ${{ matrix.compiler }}'
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: '${{ matrix.sys }} Set up MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            diffutils
            tar
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            hiredis:p
            lld:p
            ${{matrix.compiler}}:p

      - name: Set up environment
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          else
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi
          cmake_params=(-DCMAKE_BUILD_TYPE=CI)
          cmake_params+=(${{matrix.extra_cmake_params}})
          echo "CMAKE_PARAMS=${cmake_params[*]}" >> $GITHUB_ENV

      - name: Get source
        uses: actions/checkout@v4

      - name: Build and test
        run: ci/build
        continue-on-error: ${{ matrix.allow_test_failures == true &&
          steps.build-and-test.outputs.exit_status == 8 }}
        env:
          CMAKE_GENERATOR: Ninja
          TEST_CC: ${{ matrix.compiler }}

      - name: Collect testdir from failed tests
        if: failure()
        run: ci/collect-testdir

      - name: Upload testdir from failed tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.sys }}-${{ matrix.compiler }}-testdir.tar.xz
          path: testdir.tar.xz
